# server represents one virtual host

server{
    listen 80 default_server; # ipv4

    listen [::]:80 default_server; # ipv6

    server_name _;                  # works with IP address or add domain

    root /var/www/projects/rendering-deepdive/basic;
    # root root/rendering-deepdive/basic;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;   # handles SPA-style routing if needed
    }

    # serve images/css/js with caching (Optional)
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
    }
}
